### ISSUE TITLE
VBoxManage error

### ISSUE THREAD

**Issue by ThomasSwinicki** [dwatrous/hadoop-multi-server-ansible#3]
Hi, I am getting the following error when trying to vagrant up the code on a local RHEL7 environment:

```
==> master: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "bdc3df40-e6f0-4fd3-9691-3b27f7f6b3ee", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

```

From what I have gathered, this is an issue with not having VT-x or AMD-V enabled in the Ubuntu master node BIOS. That, or it doesn't allow virtualization.

Have you run into this issue before? The solution seems to be enabling VT-x and AMD-V in the master node BIOS, but I am new to Ansible and unsure on how to do that. Any help would be appreciated!

**Comment by dwatrous** [comment]
You will need to enable virtualization in your BIOS settings. This doesn't have anything to do with Ansible. It's related to VirtualBox that is trying to create a virtual host on your computer, but it fails unless virtualization is enabled.
